# Simulation config
run_until: 200001
warmup: 100000
log_interval: 24
monitor_warmup: 0
monitor_interval: 50000
# Factory config
delivery_mode: "instantly"
# Scheduler config
scheduler_interval: 48
ccr_release_limit: 5
cb_target_level: .inf

